name = "breast_cancer_test"
description = "NPU test for the breast cancer python notebook and dataset"
version = "0.1.0-dev"

authors = ["Dipen R"]
maintainers = ["Dipen R <dipenarathod@gmail.com>"]
maintainers-logins = ["dipenarathod"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
neorv32_hal = "*"
bare_runtime= "*"
ada_ml_library="*"
input_output_helper = "*"
[[pins]]
neorv32_hal = { path = ".." } 
ada_ml_library={path ="../ada_ml_library"}
input_output_helper = {path = "../input_output_helper"}


