/* Configuration for wb_ov5640_helper generated by Alire */
#ifndef WB_OV5640_HELPER_CONFIG_H
#define WB_OV5640_HELPER_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "wb_ov5640_helper"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
